[package]
name = "mlp-rs"
description = "A simple multilayer perceptron implementation in Rust."
version = "0.1.0"
edition = "2021"
author = "phasewalk1"
license = "MIT"


[dependencies]
log = "0.4.21"
ndarray = "0.14.0"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
